# Generated by Django 5.1.1 on 2024-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time')], default='Full_Time', max_length=10),
        ),
    ]
