# Generated by Django 5.1.1 on 2024-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
